server:
  port: 8082

spring:
  cloud:
    stream:
      instance-count: 1
      bindings:
        Shubham:
          group: mygroup
          binder: kafka
          destination: topic3
          consumer:
            maxAttempts: 1
            concurrency: 1
      kafka:
        binder:
          brokers:
            - localhost:9092
          consumer-properties:
            auto.offset.reset: latest
