server:
  port: 8082

spring:
  cloud:
    stream:
      instance-count: 1
      bindings:
        shubhamout:
          group: mygroup
          destination: topic3
          binder: kafka
        #shubhamout2:
          #group: mygroup
          #destination: topic3
          #binder: kafka
        Shubham:
          group: mygroup
          binder: kafka
          destination: topic3
          consumer:
            maxAttempts: 1
            concurrency: 1
      kafka:
        bindings:
          shubhamout:
            producer:
              sync: true
              configuration:
                retries: 3
                #linger.ms: 10000
                request.timeout.ms: 1000
        binder:
          brokers:
            - localhost:9092
          consumer-properties:
            auto.offset.reset: latest
